<a href="https://colab.research.google.com/github/AristarkhovZakhar/depreciation-analysis/blob/main/Xolets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [118]:
from numpy import array
import numpy as np

In [119]:
from numpy.linalg.linalg import matrix_power
#разложение Холецкого возможно для положительно определенных матриц
def xolets(matrix):
    # Проверка на положительную определенность матрицы
    matrix_ = matrix
    assert is_positive(array(matrix)) == True, "Матрица должна быть положительно определена"

    n = len(matrix)
    l=np.zeros_like(matrix)
    for j in range(n):
        for i in range(j,n):
            if i==j:
                s=0
                for k in range(j):
                    s=s+l[i,k]**2
                l[i,j]=np.sqrt(matrix[i,j]-s)
            else:
                s=0
                for k in range(j):
                    s=s+l[i,k]*l[j,k]
                l[i,j]=(matrix[i,j]-s)/l[j,j]
    return(l)



In [120]:
def backward_gauss_up1(m,target):
    n = len(m)
    solution = [0 for _ in range(n)]
    for i in range(n):
        solution[i] = target[i] / m[i][i]
        for j in range(i+1, n):
            target[j] -= m[j][i] * solution[i]
    return solution

In [121]:
def backward_gauss_down1(m,target):
    n = len(m)
    solution = [0 for _ in range(n)]
    for i in range(n - 1, -1, -1):
        solution[i] = target[i] / m[i][i]
        for j in range(i - 1, -1, -1):
            target[j] -= m[j][i] * solution[i]
    return solution

In [122]:
def backward_gauss_up2(m,target):
    n = len(m)
    l = len(m[0])
    solution = [[0 for _ in range(l)] for _ in range(n)]
    for i in range(n):
      for k in range(l-1):
        solution[i][k] = target[i][k] / m[i][i]
        for j in range(i+1, n):
          for p in range(l-1):
            target[j][p] -= m[j][i] * solution[i][p]
    return solution

In [123]:
def backward_gauss_down2(m,target):
    n = len(m)
    l = len(m[0])
    solution = [[0 for _ in range(l)] for _ in range(n)]
    for i in range(n):
      for k in range(n - 1, -1, -1):
        solution[i][k] = target[i][k] / m[i][i]
        for j in range(i - 1, -1, -1):
          for p in range(l-1):
            target[j][p] -= m[j][i] * solution[i][p]
    return solution

In [124]:
def is_positive(A):
  assert A.shape[0] == A.shape[1], "Матрица не квадратная"
  n = A.shape[0]
  for i in range(1,n+1):
    print(A[0:i,0:i])
    if np.linalg.det(A[0:i,0:i]) <= 0 :
      return False
  return True

In [125]:
def find_solution(A, B):
  L = xolets(array(A))
  L_T = list(array(L).T)
  print(B)
  if type(B[0]) is not list or len(B[0])>1:
    Y = backward_gauss_up1(L,B)
    X = backward_gauss_down1(L_T,Y)
  else:
     Y = backward_gauss_up1(L,B)
     X = backward_gauss_down1(L_T,Y)
  return X

In [126]:
m1 = [[81,-45,45],
       [-45,50,-15],
       [45,-15,38]]
target1 = [531,-460,193]

In [127]:
find_solution(m1,target1)

[[81]]
[[ 81 -45]
 [-45  50]]
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]
[531, -460, 193]


[6.0, -5.0, -4.0]

In [141]:
m2 = [[1,0,0],
      [0,1,0],
      [0,0,1]]

target2 = [[-2,0],[0,0],[1,0]]

In [142]:
find_solution(m2,target2)

[[1]]
[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[-2, 0], [0, 0], [1, 0]]


[array([-2.,  0.]), array([0., 0.]), array([1., 0.])]

In [130]:
is_positive(np.array([[1,0,0],
      [0,1,0],
      [0,0,1]]))

[[1]]
[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


True

In [139]:
def input_matrix():
  dim_A = int(input('Введите размер квадратной матрицы A--->'))
  dim_B_n = int(input('Ведите количество строк матрицы B--->'))
  dim_B_m = int(input('Ведите количество столбцов матрицы B--->'))
  print("Инициализация матрицы A--->")
  A = [[float(_) for _ in range(dim_A)] for _ in range(dim_A)]
  print("Инициализация матрицы B--->")
  B = [[float(_) for _ in range(dim_B_m)] for _ in range(dim_B_n)]
  return A,B

In [143]:
A, B = input_matrix()

KeyboardInterrupt: ignored

In [ ]:
find_solution(A,B)